	git add source/Async/PeanutButter.Async.NugetPackage/Package.nuspec
	git add source/Async/PeanutButter.TestUtils.Async.NugetPackage/Package.nuspec
	git add source/DatabaseHelpers/PeanutButter.DatabaseHelpers.NugetPackage/Package.nuspec
	git add source/DatabaseHelpers/PeanutButter.DatabaseHelpers.Testability.NugetPackage/Package.nuspec
	git add source/EmailSpooler/EmailSpooler.Win32Service.DB.NugetPackage/Package.nuspec
	git add source/EmailSpooler/EmailSpooler.Win32Service.Entity.NugetPackage/Package.nuspec
	git add source/INI/PeanutButter.INI.NugetPackage/Package.nuspec
	git add source/SimpleServers/PeanutButter.SimpleHTTPServer.NugetPackage/Package.nuspec
	git add source/SimpleServers/PeanutButter.SimpleHTTPServer.Testability.NugetPackage/Package.nuspec
	git add source/SimpleServers/PeanutButter.SimpleTcpServer.NugetPackage/Package.nuspec
	git add source/TempDb/PeanutButter.TempDb.LocalDb.NugetPackage/Package.nuspec
	git add source/TempDb/PeanutButter.TempDb.NugetPackage/Package.nuspec
	git add source/TempDb/PeanutButter.TempDb.SqlCe.NugetPackage/Package.nuspec
	git add source/TempDb/PeanutButter.TempDb.Sqlite.NugetPackage/Package.nuspec
	git add source/TestUtils/PeanutButter.RandomGenerators.NugetPackage/Package.nuspec
	git add source/TestUtils/PeanutButter.TestUtils.Entity.NugetPackage/Package.nuspec
	git add source/TestUtils/PeanutButter.TestUtils.Generic.NugetPackage/Package.nuspec
	git add source/TestUtils/PeanutButter.TestUtils.MVC.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.DuckTyping.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.FluentMigrator.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.TinyEventAggregator.NuGetPackage/Package.nuspec
	git add source/Utils/PeanutButter.TrayIcon.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.Utils.Entity.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.Utils.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.Utils.Windsor.NugetPackage/Package.nuspec
	git add source/Utils/PeanutButter.XmlUtils.NuGetPackage/Package.nuspec
	git add source/Win32Service/PeanutButter.ServiceShell.NugetPackage/Package.nuspec
	git add source/Win32Service/PeanutButter.WindowsServiceManagement.NugetPackage/Package.nuspec
