//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeanutButter.TestUtils.Entity.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeanutButter.TestUtils.Entity.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Object:  Table [dbo].[COMBlockList]    Script Date: 25 Nov 2015 9:23:57 AM ******/
        ///CREATE TABLE [dbo].[COMBlockList](
        ///                [COMBlockListID] [int] IDENTITY(1,1) NOT NULL,
        ///                [COMBlockListReasonID] [int] NOT NULL,
        ///                [COREClientID] [int] NOT NULL,
        ///                [Source] [nvarchar](250) NOT NULL,
        ///                [SourceBy] [int] NULL,
        ///                [Date] [datetime] NOT NULL,
        ///                [COMBulkID] [int] NULL,
        ///                [CORECustomerID] [int] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbscript {
            get {
                return ResourceManager.GetString("dbscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table [SomeEntityWithDecimalValue] (
        ///    SomeEntityWithDecimalValueId int identity primary key,
        ///    DecimalValue decimal not null,
        ///    Created datetime not null default CURRENT_TIMESTAMP,
        ///    Enabled bit not null default 1,
        ///    LastUpdated datetime null
        ///);
        ///GO
        ///
        ///.
        /// </summary>
        internal static string entitypersistence {
            get {
                return ResourceManager.GetString("entitypersistence", resourceCulture);
            }
        }
    }
}
