//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NugetPackageVersionIncrementer.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NugetPackageVersionIncrementer.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;package&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;PeanutButter.TestUtils.Entity&lt;/id&gt;
        ///    &lt;version&gt;1.1.33&lt;/version&gt;
        ///    &lt;title&gt;PeanutButter.TestUtils.Entity&lt;/title&gt;
        ///    &lt;authors&gt;davyd&lt;/authors&gt;
        ///    &lt;owners&gt;&lt;/owners&gt;
        ///    &lt;description&gt;
        ///    Contains classes to help with testing when entity and a SQL Server would be involved in production:
        ///    * TestFixtureWithTempDb provides bootstrapping for tests which would use a temporary database (TempDBLocalDb)
        ///    * EntityPersistenceTestFixtureBase provides helpers for the common [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string package1 {
            get {
                return ResourceManager.GetString("package1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;package&gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;PeanutButter.DatabaseHelpers&lt;/id&gt;
        ///    &lt;version&gt;1.1.33&lt;/version&gt;
        ///    &lt;title&gt;PeanutButter.DatabaseHelpers&lt;/title&gt;
        ///    &lt;authors&gt;Davyd McColl&lt;/authors&gt;
        ///    &lt;owners&gt;Davyd McColl&lt;/owners&gt;
        ///    &lt;description&gt;
        ///      The Database Helpers component of the Peanut Butter mini-suite
        ///    &lt;/description&gt;
        ///    &lt;releaseNotes&gt;&lt;/releaseNotes&gt;
        ///    &lt;summary&gt;
        ///      Provides statement builders for Select, Insert, Update and Delete, compliant with MSSQL, SqlCE, Access, and, more
        ///      recent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string package2 {
            get {
                return ResourceManager.GetString("package2", resourceCulture);
            }
        }
    }
}
